site_name: pyxecm

site_url: https://example.com/

theme:
  name: "material"
  logo: https://avatars.githubusercontent.com/u/6463527?s=200&v=4
  favicon: https://avatars.githubusercontent.com/u/6463527?s=200&v=4
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - mkdocstrings
  - git-revision-date-localized:
      enable_creation_date: true

repo_url: https://github.com/opentext/pyxecm
repo_name: opentext/pyxecm
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Index: index.md
  - Payload Syntax: payload-syntax.md
  - Extended ECM Python Classes:
      - Content Server (OTCS): pyxecm/otcs.md
      - Directory Services (OTDS): pyxecm/otds.md
      - Archive Center (OTAC): pyxecm/otac.md
      - Intelligent Viewing (OTIV): pyxecm/otiv.md
      - PowerDocs (OTPD): pyxecm/otpd.md
  - Customizer Python Classes:
      - Payload: pyxecm/payload.md
      - Customizer: pyxecm/customizer.md
      - Browser Automation: pyxecm/browser.md
      - K8s: pyxecm/k8s.md
      - Microsoft 365: pyxecm/m365.md
      - SAP: pyxecm/sap.md
      - Translate: pyxecm/translate.md
  - Helper Python Classes:
      - Assoc: pyxecm/assoc.md
      - Web: pyxecm/web.md
      - XML: pyxecm/xml.md
