site_name: pyxecm

site_url: https://opentext.github.io/pyxecm/

theme:
  name: "material"
  logo: https://avatars.githubusercontent.com/u/6463527?s=200&v=4
  favicon: https://avatars.githubusercontent.com/u/6463527?s=200&v=4
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips

plugins:
  - search
  - mkdocstrings

repo_url: https://github.com/opentext/pyxecm
repo_name: opentext/pyxecm
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Index: index.md
  - pyxecm:
      - Archive Center (OTAC): pyxecm/otac.md
      - Aviator Search: pyxecm/avts.md
      - Content Server (OTCS): pyxecm/otcs.md
      - Core Share: pyxecm/coreshare.md
      - Directory Services (OTDS): pyxecm/otds.md
      - Intelligent Viewing (OTIV): pyxecm/otiv.md
      - Media Management (OTMM): pyxecm/otmm.md
      - PowerDocs (OTPD): pyxecm/otpd.md
      - Helper Python Classes:
          - Assoc: pyxecm/assoc.md
          - Data: pyxecm/data.md
          - Web: pyxecm/web.md
          - XML: pyxecm/xml.md
  - pyxecm-api:
      - API: pyxecm/api.md
      - API Settings: customizerapisettings.md
  - pyxecm-customizer:
      - Customizer: pyxecm/customizer.md
      - Customizer Settings: customizersettings.md
      - Browser Automation: pyxecm/browser.md
      - Payload: pyxecm/payload.md
      - Payload Syntax: payload-syntax.md
      - K8s: pyxecm/k8s.md
      - Microsoft 365: pyxecm/m365.md
      - Salesforce: pyxecm/salesforce.md
      - SAP: pyxecm/sap.md
      - SuccessFactors: pyxecm/successfactors.md
      - Translate: pyxecm/translate.md
