site_name: pyxecm

site_url: https://example.com/

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    primary: black
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link    

plugins:
  - search
  - mkdocstrings
  - git-revision-date-localized:
      enable_creation_date: true

repo_url: https://gitlab.otxlab.net/ecm/pyxecm/
repo_name: ecm/pyxecm
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
        
nav:
  - Index: index.md
  - Payload Syntax: payload-syntax.md
  - xECM Classes:
    - OTCS: pyxecm/otcs.md
    - OTDS: pyxecm/otds.md  
    - OTAC: pyxecm/otac.md  
    - OTIV: pyxecm/otiv.md  
    - OTPD: pyxecm/otpd.md  
  - Customizer Classes:
    - Payload: pyxecm/payload.md  
    - Browser Automation: pyxecm/browser.md
    - Customizer: pyxecm/customizer.md    
    - K8s: pyxecm/k8s.md
    - M365: pyxecm/m365.md
    - Translate: pyxecm/translate.md
    - SAP: pyxecm/sap.md
  - Changelog: changelog.md
