site_name: pyxecm
site_description: Python library to interact with the OpenText Content Management REST APIs

site_url: https://opentext.github.io/pyxecm/

theme:
  name: "material"
  logo: https://avatars.githubusercontent.com/u/6463527?s=200&v=4
  favicon: https://avatars.githubusercontent.com/u/6463527?s=200&v=4
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            heading_level: 2
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            filters: ["!^_"]
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
            show_source: true
            summary: true

repo_url: https://github.com/opentext/pyxecm
repo_name: opentext/pyxecm
edit_uri: edit/main/docs/

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - pyxecm:
      - Overview: pyxecm/index.md
      - Archive Center (OTAC): pyxecm/otac.md
      - Aviator Search (AVTS): pyxecm/avts.md
      - Content Server (OTCS): pyxecm/otcs.md
      - Core Share: pyxecm/coreshare.md
      - Directory Services (OTDS): pyxecm/otds.md
      - Intelligent Viewing (OTIV): pyxecm/otiv.md
      - Media Management (OTMM): pyxecm/otmm.md
      - PowerDocs (OTPD): pyxecm/otpd.md
      - Helper Classes: pyxecm/helper.md

  - pyxecm-api:
      - API: pyxecm-api/index.md
      - API Settings: pyxecm-api/settings.md

  - pyxecm-customizer:
      - Customizer: pyxecm-customizer/index.md
      - Customizer Settings: pyxecm-customizer/settings.md
      - Payload: pyxecm-customizer/payload.md
      - Payload Syntax: pyxecm-customizer/payload-syntax.md
      - Browser Automation: pyxecm-customizer/browser.md
      - K8s: pyxecm-customizer/k8s.md
      - Microsoft 365: pyxecm-customizer/m365.md
      - Salesforce: pyxecm-customizer/salesforce.md
      - SAP: pyxecm-customizer/sap.md
      - SuccessFactors: pyxecm-customizer/successfactors.md
      - Translate: pyxecm-customizer/translate.md
